export const ADD_NEW_COMPANY = 'ADD_NEW_COMPANY';
export const REMOVE_COMPANY = 'REMOVE_COMPANY';
export const ADD_NEW_SUBSIDIARY = 'ADD_NEW_SUBSIDIARY';
export const EDIT_SUBSIDIARY = 'EDIT_SUBSIDIARY';
export const REMOVE_SUBSIDIARY = 'REMOVE_SUBSIDIARY';
export const EDIT_COMPANY = 'EDIT_COMPANY';
